title: Chendi Li
url: "https://www.chendi.gq"
#baseurl: "/researcher"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./ict.png"
favicon: "./ict-removebg-preview.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/Mastli"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/researcher/"
 - name: "Resume"
   link: "Chendi_Li_Resume.pdf"
# - name: "CV"
#   link: "Chendi_Li_CV.pdf"
# - name: "Contact"
#   link: "Contact"
# - name: "Publication"
#   link: "Publication"
#